/*
 * ramn_screen_stats.c
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2025 TOYOTA MOTOR CORPORATION.
 * ALL RIGHTS RESERVED.</center></h2>
 *
 * This software component is licensed by TOYOTA MOTOR CORPORATION under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */


#include "ramn_screen_stats.h"

#ifdef ENABLE_SCREEN

static void SCREENSTATS_Init()
{
	RAMN_SCREENUTILS_DrawBase();
	RAMN_SPI_RefreshString(90,5, RAMN_SCREENUTILS_COLORTHEME.LIGHT, RAMN_SCREENUTILS_COLORTHEME.BACKGROUND, "STATS");
	RAMN_SPI_RefreshString(7,5+16, RAMN_SCREENUTILS_COLORTHEME.LIGHT, RAMN_SCREENUTILS_COLORTHEME.BACKGROUND, "CAN RX  : 0x");
	RAMN_SPI_RefreshString(7,5+32, RAMN_SCREENUTILS_COLORTHEME.LIGHT, RAMN_SCREENUTILS_COLORTHEME.BACKGROUND, "CAN TX  : 0x");
	RAMN_SPI_RefreshString(7,5+48, RAMN_SCREENUTILS_COLORTHEME.LIGHT, RAMN_SCREENUTILS_COLORTHEME.BACKGROUND, "CAN ERR : 0x");
	RAMN_SPI_RefreshString(7,5+64, RAMN_SCREENUTILS_COLORTHEME.LIGHT, RAMN_SCREENUTILS_COLORTHEME.BACKGROUND, "CAN OVF :");
	RAMN_SPI_RefreshString(7,5+80, RAMN_SCREENUTILS_COLORTHEME.LIGHT, RAMN_SCREENUTILS_COLORTHEME.BACKGROUND, "CAN BUS :");
	RAMN_SPI_RefreshString(7,5+112, RAMN_SCREENUTILS_COLORTHEME.LIGHT, RAMN_SCREENUTILS_COLORTHEME.BACKGROUND, "USB ERR : 0x");
#ifdef ENABLE_CDC
	RAMN_SPI_RefreshString(7,5+128, RAMN_SCREENUTILS_COLORTHEME.LIGHT, RAMN_SCREENUTILS_COLORTHEME.BACKGROUND, "CDC OVF : 0x");
#endif
#ifdef ENABLE_GSUSB
	RAMN_SPI_RefreshString(7,5+144, RAMN_SCREENUTILS_COLORTHEME.LIGHT, RAMN_SCREENUTILS_COLORTHEME.BACKGROUND, "QUE ERR : 0x");
#endif
	RAMN_SPI_RefreshString(7,5+160, RAMN_SCREENUTILS_COLORTHEME.LIGHT, RAMN_SCREENUTILS_COLORTHEME.BACKGROUND, "SYSTICK : 0x");
}

static void SCREENSTATS_Update(uint32_t tick)
{
	if (RAMN_SCREENUTILS_LoopCounter % 5U == 0U)
	{
		RAMN_SPI_RefreshUint32(7+12*11,5+16, RAMN_SCREENUTILS_COLORTHEME.LIGHT, RAMN_SCREENUTILS_COLORTHEME.BACKGROUND, RAMN_FDCAN_Status.CANRXCnt);
		RAMN_SPI_RefreshUint32(7+12*11,5+32, RAMN_SCREENUTILS_COLORTHEME.LIGHT, RAMN_SCREENUTILS_COLORTHEME.BACKGROUND, RAMN_FDCAN_Status.CANTXSentCnt);

		if (RAMN_FDCAN_Status.CANErrCnt > 0) RAMN_SPI_RefreshUint32(7+12*11,5+48, RAMN_SCREENUTILS_COLORTHEME.WHITE, RAMN_SCREENUTILS_COLORTHEME.BACKGROUND, RAMN_FDCAN_Status.CANErrCnt);
		else RAMN_SPI_RefreshUint32(7+12*11,5+48, RAMN_SCREENUTILS_COLORTHEME.LIGHT, RAMN_SCREENUTILS_COLORTHEME.BACKGROUND, RAMN_FDCAN_Status.CANErrCnt);

		if (RAMN_FDCAN_Status.CANRxOverrunCnt > 0) RAMN_SPI_RefreshString(7+10*11,5+64, RAMN_SCREENUTILS_COLORTHEME.WHITE, RAMN_SCREENUTILS_COLORTHEME.BACKGROUND, "YES");
		else RAMN_SPI_RefreshString(7+10*11,5+64, RAMN_SCREENUTILS_COLORTHEME.LIGHT, RAMN_SCREENUTILS_COLORTHEME.BACKGROUND, "NO");

		if (RAMN_FDCAN_Status.busOff != False) RAMN_SPI_RefreshString(7+10*11,5+80, RAMN_SCREENUTILS_COLORTHEME.WHITE, RAMN_SCREENUTILS_COLORTHEME.BACKGROUND, "OFF");
		else RAMN_SPI_RefreshString(7+10*11,5+80, RAMN_SCREENUTILS_COLORTHEME.LIGHT, RAMN_SCREENUTILS_COLORTHEME.BACKGROUND, "ON");

#ifdef ENABLE_USB
		if (RAMN_USB_Config.USBErrCnt > 0) RAMN_SPI_RefreshUint32(7+12*11,5+112, RAMN_SCREENUTILS_COLORTHEME.WHITE, RAMN_SCREENUTILS_COLORTHEME.BACKGROUND, RAMN_USB_Config.USBErrCnt);
		else RAMN_SPI_RefreshUint32(7+12*11,5+112, RAMN_SCREENUTILS_COLORTHEME.LIGHT, RAMN_SCREENUTILS_COLORTHEME.BACKGROUND, RAMN_USB_Config.USBErrCnt);
#endif

#ifdef ENABLE_CDC
		if (RAMN_USB_Config.USBTxOverflowCnt > 0) RAMN_SPI_RefreshUint32(7+12*11,5+128, RAMN_SCREENUTILS_COLORTHEME.WHITE, RAMN_SCREENUTILS_COLORTHEME.BACKGROUND, RAMN_USB_Config.USBTxOverflowCnt);
		else RAMN_SPI_RefreshUint32(7+12*11,5+128, RAMN_SCREENUTILS_COLORTHEME.LIGHT, RAMN_SCREENUTILS_COLORTHEME.BACKGROUND, RAMN_USB_Config.USBTxOverflowCnt);
#endif

#ifdef ENABLE_GSUSB
		if (RAMN_USB_Config.queueErrorCnt > 0) RAMN_SPI_RefreshUint32(7+12*11,5+144, RAMN_SCREENUTILS_COLORTHEME.WHITE, RAMN_SCREENUTILS_COLORTHEME.BACKGROUND, RAMN_USB_Config.queueErrorCnt);
		else RAMN_SPI_RefreshUint32(7+12*11,5+144, RAMN_SCREENUTILS_COLORTHEME.LIGHT, RAMN_SCREENUTILS_COLORTHEME.BACKGROUND, RAMN_USB_Config.queueErrorCnt);
#endif

		RAMN_SPI_RefreshUint32(7+12*11,5+160, RAMN_SCREENUTILS_COLORTHEME.LIGHT, RAMN_SCREENUTILS_COLORTHEME.BACKGROUND, tick);

		RAMN_SCREENUTILS_DrawSubconsoleUpdate();
	}
}

RAMNScreen_t ScreenStats = {
		.Init = SCREENSTATS_Init,
		.Update = SCREENSTATS_Update,
		.Deinit = 0U,
		.UpdateInput = 0U,
		.ProcessRxCANMessage = 0U
};

#endif
