M48
; DRILL file {KiCad 7.0.10} date Tue Apr 23 18:14:46 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-04-23T18:14:46+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0315
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X1.7815Y-2.2266
X1.7815Y-2.4234
T2
X1.75Y-1.85
X1.75Y-3.675
X4.825Y-1.85
X4.825Y-3.675
M30
