M48
; DRILL file {KiCad 7.0.9} date Wed Jan 29 12:58:40 2025
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-01-29T12:58:40-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0295
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0413
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1260
%
G90
G05
T1
X1.5757Y-1.3143
T2
X1.6815Y-1.2085
T3
X1.4Y-0.935
X2.69Y-0.935
T0
M30
