/*
 * ramn_vehicle_specific.h
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2025 TOYOTA MOTOR CORPORATION.
 * ALL RIGHTS RESERVED.</center></h2>
 *
 * This software component is licensed by TOYOTA MOTOR CORPORATION under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

// This modules defines value which are specific to one vehicle, such as CAN IDs and CAN message payload formats.

#ifndef INC_RAMN_VEHICLE_SPECIFIC_H_
#define INC_RAMN_VEHICLE_SPECIFIC_H_

#include "main.h"

/////////////////////////////////////////
// VEHICLE SPECIFIC DEFINITIONS START  //
/////////////////////////////////////////

// Highest gear that can be selected
#define MAX_GEAR_VALUE 0x06

// Default CAN Message format
#define CAN_MAX_PAYLOAD_SIZE_DEFAULT 	8

// Data-driven definitions for default message format fields
#define RAMN_MSG_PAYLOAD_MASK        0xFFFF
#define RAMN_MSG_PAYLOAD_OFFSET      0
#define RAMN_MSG_COUNTER_MASK        0xFFFF
#define RAMN_MSG_COUNTER_OFFSET      16
#define RAMN_MSG_CRC_MASK            0xFFFFFFFF
#define RAMN_MSG_CRC_OFFSET          32

// Definition of Diagnostic IDs
// Note that ISO-TP standard recommends that 0x7e0/0x7e8 pair be assigned to ECM (Engine Control Module) and that 0x7e1/0x7e9 be assigned to TCM (Transmission Control Module)
#if defined(ENABLE_DIAG)

#ifdef ENABLE_UDS
#define UDS_FUNCTIONAL_RX_CANID 0x7df
#endif

#if defined(TARGET_ECUA)

#if defined(ENABLE_UDS)
#define UDS_RX_CANID 0x7e0
#define UDS_TX_CANID UDS_RX_CANID+8
#endif
#if defined(ENABLE_KWP)
#define KWP_RX_CANID 0x7e4
#define KWP_TX_CANID KWP_RX_CANID+8
#endif
#if defined(ENABLE_XCP)
#define XCP_RX_CANID 0x550
#define XCP_TX_CANID XCP_RX_CANID+1
#endif

#elif defined(TARGET_ECUB)

#if defined(ENABLE_UDS)
#define UDS_RX_CANID 0x7e1
#define UDS_TX_CANID UDS_RX_CANID+8
#endif
#if defined(ENABLE_KWP)
#define KWP_RX_CANID 0x7e5
#define KWP_TX_CANID KWP_RX_CANID+8
#endif
#if defined(ENABLE_XCP)
#define XCP_RX_CANID 0x552
#define XCP_TX_CANID XCP_RX_CANID+1
#endif

#elif defined(TARGET_ECUC)

#if defined(ENABLE_UDS)
#define UDS_RX_CANID 0x7e2
#define UDS_TX_CANID UDS_RX_CANID+8
#endif
#if defined(ENABLE_KWP)
#define KWP_RX_CANID 0x7e6
#define KWP_TX_CANID KWP_RX_CANID+8
#endif
#if defined(ENABLE_XCP)
#define XCP_RX_CANID 0x554
#define XCP_TX_CANID XCP_RX_CANID+1
#endif

#elif defined(TARGET_ECUD)

#if defined(ENABLE_UDS)
#define UDS_RX_CANID 0x7e3
#define UDS_TX_CANID UDS_RX_CANID+8
#endif
#if defined(ENABLE_KWP)
#define KWP_RX_CANID 0x7e7
#define KWP_TX_CANID KWP_RX_CANID+8
#endif
#if defined(ENABLE_XCP)
#define XCP_RX_CANID 0x556
#define XCP_TX_CANID XCP_RX_CANID+1
#endif

#endif

#endif

// Default Settings for all messages
#define CAN_SIM_PERIODSMS_DEFAULT						100				   // Period for slow messages
#define CAN_SIM_PERIODSMS_DEFAULT_FAST					10				   // Period for fast messages
#define CAN_SIM_IDTYPE_DEFAULT    						FDCAN_STANDARD_ID  // Standard ID or Extended ID
#define CAN_SIM_FORMAT_DEFAULT    						FDCAN_CLASSIC_CAN  // Classic CAN or CAN-FD
#define CAN_SIM_BRS_DEFAULT       						FDCAN_BRS_OFF      // Bit rate switching ON or OFF
#define CAN_SIM_DLC_DEFAULT   							FDCAN_DLC_BYTES_8  // Default CAN payload size

// Message specific settings
#ifdef ENABLE_J1939_MODE
  #include "ramn_j1939.h"

  #define J1939_ID(prio, edp, dp, pf, ps_da, sa) \
      ((((prio) & 0x7) << 26) | \
       (((edp) & 0x1) << 25) | \
       (((dp) & 0x1) << 24) | \
       (((pf) & 0xFF) << 16) | \
       (((ps_da) & 0xFF) << 8) | \
       ((sa) & 0xFF))

  /* Verification for PDU1 broadcast (DA=255) */
  #define J1939_CHECK_PDU1_DA J1939_ID(6, 0, 0, 2, 255, 11)
  #if ((J1939_CHECK_PDU1_DA >> 8) & 0xFF) != 0xFF
    #error "J1939_ID macro failed to correctly insert DA=255 in bits 8-15"
  #endif

  #define J1939_UCAST_ID(prio, pgn, da, sa) \
      J1939_ID((prio), 0, ((pgn) >> 16) & 0x1, ((pgn) >> 8) & 0xFF, (da), (sa))

  #define J1939_BCAST_ID(prio, pgn, sa) \
      J1939_ID((prio), 0, ((pgn) >> 16) & 0x1, ((pgn) >> 8) & 0xFF, (pgn) & 0xFF, (sa))

  #define CAN_SIM_J1939_IDTYPE      FDCAN_EXTENDED_ID
  #define CAN_SIM_J1939_FORMAT      FDCAN_CLASSIC_CAN
  #define CAN_SIM_J1939_BRS         FDCAN_BRS_OFF
  #define CAN_SIM_J1939_DLC         FDCAN_DLC_BYTES_8

  /* J1939 Settings for RAMN Messages */

  #define CAN_SIM_CONTROL_BRAKE_CANID     J1939_BCAST_ID(6, J1939_PGN_EBC1, J1939_SA_POWERTRAIN_CTRL)
  #define CAN_SIM_CONTROL_BRAKE_PERIODMS  100
  #define CAN_SIM_CONTROL_BRAKE_IDTYPE    CAN_SIM_J1939_IDTYPE
  #define CAN_SIM_CONTROL_BRAKE_FORMAT    CAN_SIM_J1939_FORMAT
  #define CAN_SIM_CONTROL_BRAKE_BRS       CAN_SIM_J1939_BRS
  #define CAN_SIM_CONTROL_BRAKE_DLC       CAN_SIM_J1939_DLC
  #define CAN_SIM_CONTROL_BRAKE_PAYLOAD_OFFSET -1
  #define CAN_SIM_CONTROL_BRAKE_COUNTER_OFFSET -1
  #define CAN_SIM_CONTROL_BRAKE_CRC_OFFSET -1

  #define CAN_SIM_CONTROL_ACCEL_CANID     J1939_BCAST_ID(6, J1939_PGN_EEC2, J1939_SA_POWERTRAIN_CTRL)
  #define CAN_SIM_CONTROL_ACCEL_PERIODMS  50
  #define CAN_SIM_CONTROL_ACCEL_IDTYPE    CAN_SIM_J1939_IDTYPE
  #define CAN_SIM_CONTROL_ACCEL_FORMAT    CAN_SIM_J1939_FORMAT
  #define CAN_SIM_CONTROL_ACCEL_BRS       CAN_SIM_J1939_BRS
  #define CAN_SIM_CONTROL_ACCEL_DLC       CAN_SIM_J1939_DLC
  #define CAN_SIM_CONTROL_ACCEL_PAYLOAD_OFFSET -1
  #define CAN_SIM_CONTROL_ACCEL_COUNTER_OFFSET -1
  #define CAN_SIM_CONTROL_ACCEL_CRC_OFFSET -1

  #define CAN_SIM_CONTROL_STEERING_CANID  J1939_BCAST_ID(6, J1939_PGN_VDC2, J1939_SA_STEERING_CTRL)
  #define CAN_SIM_CONTROL_STEERING_PERIODMS 10
  #define CAN_SIM_CONTROL_STEERING_IDTYPE CAN_SIM_J1939_IDTYPE
  #define CAN_SIM_CONTROL_STEERING_FORMAT CAN_SIM_J1939_FORMAT
  #define CAN_SIM_CONTROL_STEERING_BRS    CAN_SIM_J1939_BRS
  #define CAN_SIM_CONTROL_STEERING_DLC    CAN_SIM_J1939_DLC
  #define CAN_SIM_CONTROL_STEERING_PAYLOAD_OFFSET -1
  #define CAN_SIM_CONTROL_STEERING_COUNTER_OFFSET -1
  #define CAN_SIM_CONTROL_STEERING_CRC_OFFSET -1

  #define CAN_SIM_CONTROL_SHIFT_CANID     J1939_BCAST_ID(6, J1939_PGN_ETC2, J1939_SA_TRANSMISSION)
  #define CAN_SIM_CONTROL_SHIFT_PERIODMS  100
  #define CAN_SIM_CONTROL_SHIFT_IDTYPE    CAN_SIM_J1939_IDTYPE
  #define CAN_SIM_CONTROL_SHIFT_FORMAT    CAN_SIM_J1939_FORMAT
  #define CAN_SIM_CONTROL_SHIFT_BRS       CAN_SIM_J1939_BRS
  #define CAN_SIM_CONTROL_SHIFT_DLC       CAN_SIM_J1939_DLC
  #define CAN_SIM_CONTROL_SHIFT_PAYLOAD_OFFSET -1
  #define CAN_SIM_CONTROL_SHIFT_COUNTER_OFFSET -1
  #define CAN_SIM_CONTROL_SHIFT_CRC_OFFSET -1

  #define CAN_SIM_JOYSTICK_BUTTONS_CANID  J1939_BCAST_ID(6, J1939_PGN_PROPB_65282, J1939_SA_SHIFT_CONSOLE)
  #define CAN_SIM_JOYSTICK_BUTTONS_PERIODMS 50
  #define CAN_SIM_JOYSTICK_BUTTONS_IDTYPE CAN_SIM_J1939_IDTYPE
  #define CAN_SIM_JOYSTICK_BUTTONS_FORMAT CAN_SIM_J1939_FORMAT
  #define CAN_SIM_JOYSTICK_BUTTONS_BRS    CAN_SIM_J1939_BRS
  #define CAN_SIM_JOYSTICK_BUTTONS_DLC    8 // 8 bytes for 4 2-bit fields + 1 2-bit field
  #define CAN_SIM_JOYSTICK_BUTTONS_PAYLOAD_OFFSET -1
  #define CAN_SIM_JOYSTICK_BUTTONS_COUNTER_OFFSET -1
  #define CAN_SIM_JOYSTICK_BUTTONS_CRC_OFFSET -1

  #define CAN_SIM_COMMAND_HORN_CANID            J1939_BCAST_ID(6, J1939_PGN_CM3, J1939_SA_POWERTRAIN_CTRL)
  #define CAN_SIM_COMMAND_HORN_CANID_PERIODMS   100
  #define CAN_SIM_COMMAND_HORN_CANID_IDTYPE     CAN_SIM_J1939_IDTYPE
  #define CAN_SIM_COMMAND_HORN_CANID_FORMAT     CAN_SIM_J1939_FORMAT
  #define CAN_SIM_COMMAND_HORN_CANID_BRS        CAN_SIM_J1939_BRS
  #define CAN_SIM_COMMAND_HORN_CANID_DLC        CAN_SIM_J1939_DLC
  #define CAN_SIM_COMMAND_HORN_PAYLOAD_OFFSET   -1
  #define CAN_SIM_COMMAND_HORN_COUNTER_OFFSET   -1
  #define CAN_SIM_COMMAND_HORN_CRC_OFFSET       -1

  #define CAN_SIM_CONTROL_SIDEBRAKE_CANID J1939_BCAST_ID(6, J1939_PGN_B1, J1939_SA_BRAKES_DRIVE_AXLE_1)
  #define CAN_SIM_CONTROL_SIDEBRAKE_PERIODMS 1000
  #define CAN_SIM_CONTROL_SIDEBRAKE_IDTYPE CAN_SIM_J1939_IDTYPE
  #define CAN_SIM_CONTROL_SIDEBRAKE_FORMAT CAN_SIM_J1939_FORMAT
  #define CAN_SIM_CONTROL_SIDEBRAKE_BRS    CAN_SIM_J1939_BRS
  #define CAN_SIM_CONTROL_SIDEBRAKE_DLC    CAN_SIM_J1939_DLC
  #define CAN_SIM_CONTROL_SIDEBRAKE_PAYLOAD_OFFSET -1
  #define CAN_SIM_CONTROL_SIDEBRAKE_COUNTER_OFFSET -1
  #define CAN_SIM_CONTROL_SIDEBRAKE_CRC_OFFSET -1

  #define CAN_SIM_COMMAND_TURNINDICATOR_CANID J1939_BCAST_ID(3, J1939_PGN_OEL, J1939_SA_SHIFT_CONSOLE)
  #define CAN_SIM_COMMAND_TURNINDICATOR_PERIODMS 100
  #define CAN_SIM_COMMAND_TURNINDICATOR_IDTYPE CAN_SIM_J1939_IDTYPE
  #define CAN_SIM_COMMAND_TURNINDICATOR_FORMAT CAN_SIM_J1939_FORMAT
  #define CAN_SIM_COMMAND_TURNINDICATOR_BRS    CAN_SIM_J1939_BRS
  #define CAN_SIM_COMMAND_TURNINDICATOR_DLC    CAN_SIM_J1939_DLC
  #define CAN_SIM_COMMAND_TURNINDICATOR_PAYLOAD_OFFSET -1
  #define CAN_SIM_COMMAND_TURNINDICATOR_COUNTER_OFFSET -1
  #define CAN_SIM_COMMAND_TURNINDICATOR_CRC_OFFSET -1

  #define CAN_SIM_CONTROL_ENGINEKEY_CANID J1939_BCAST_ID(6, J1939_PGN_CM3, J1939_SA_BODY_CTRL)
  #define CAN_SIM_CONTROL_ENGINEKEY_PERIODMS 100
  #define CAN_SIM_CONTROL_ENGINEKEY_IDTYPE CAN_SIM_J1939_IDTYPE
  #define CAN_SIM_CONTROL_ENGINEKEY_FORMAT CAN_SIM_J1939_FORMAT
  #define CAN_SIM_CONTROL_ENGINEKEY_BRS    CAN_SIM_J1939_BRS
  #define CAN_SIM_CONTROL_ENGINEKEY_DLC    CAN_SIM_J1939_DLC
  #define CAN_SIM_CONTROL_ENGINEKEY_PAYLOAD_OFFSET -1
  #define CAN_SIM_CONTROL_ENGINEKEY_COUNTER_OFFSET -1
  #define CAN_SIM_CONTROL_ENGINEKEY_CRC_OFFSET -1

  #define CAN_SIM_COMMAND_LIGHTS_CANID    J1939_BCAST_ID(3, J1939_PGN_LIGHTS_CMD, J1939_SA_CHASSIS_CTRL_1)
  #define CAN_SIM_COMMAND_LIGHTS_PERIODMS 100
  #define CAN_SIM_COMMAND_LIGHTS_IDTYPE   CAN_SIM_J1939_IDTYPE
  #define CAN_SIM_COMMAND_LIGHTS_FORMAT   CAN_SIM_J1939_FORMAT
  #define CAN_SIM_COMMAND_LIGHTS_BRS      CAN_SIM_J1939_BRS
  #define CAN_SIM_COMMAND_LIGHTS_DLC      CAN_SIM_J1939_DLC
  #define CAN_SIM_COMMAND_LIGHTS_PAYLOAD_OFFSET -1
  #define CAN_SIM_COMMAND_LIGHTS_COUNTER_OFFSET -1
  #define CAN_SIM_COMMAND_LIGHTS_CRC_OFFSET -1

  #define CAN_SIM_CONTROL_LIGHTS_CANID    J1939_BCAST_ID(6, J1939_PGN_PROPB_65280, J1939_SA_BODY_CTRL)
  #define CAN_SIM_CONTROL_LIGHTS_PERIODMS 100
  #define CAN_SIM_CONTROL_LIGHTS_IDTYPE   CAN_SIM_J1939_IDTYPE
  #define CAN_SIM_CONTROL_LIGHTS_FORMAT   CAN_SIM_J1939_FORMAT
  #define CAN_SIM_CONTROL_LIGHTS_BRS      CAN_SIM_J1939_BRS
  #define CAN_SIM_CONTROL_LIGHTS_DLC      CAN_SIM_J1939_DLC
  #define CAN_SIM_CONTROL_LIGHTS_PAYLOAD_OFFSET -1
  #define CAN_SIM_CONTROL_LIGHTS_COUNTER_OFFSET -1
  #define CAN_SIM_CONTROL_LIGHTS_CRC_OFFSET -1

  #define CAN_SIM_COMMAND_BRAKE_CANID     J1939_UCAST_ID(1, J1939_PGN_XBR, J1939_DA_BRAKE_SYSTEM, J1939_SA_HEADWAY_CTRL)
  #define CAN_SIM_COMMAND_BRAKE_PERIODMS  20
  #define CAN_SIM_COMMAND_BRAKE_IDTYPE    CAN_SIM_J1939_IDTYPE
  #define CAN_SIM_COMMAND_BRAKE_FORMAT    CAN_SIM_J1939_FORMAT
  #define CAN_SIM_COMMAND_BRAKE_BRS       CAN_SIM_J1939_BRS
  #define CAN_SIM_COMMAND_BRAKE_DLC       CAN_SIM_J1939_DLC
  #define CAN_SIM_COMMAND_BRAKE_PAYLOAD_OFFSET -1
  #define CAN_SIM_COMMAND_BRAKE_COUNTER_OFFSET -1
  #define CAN_SIM_COMMAND_BRAKE_CRC_OFFSET -1

  #define CAN_SIM_COMMAND_ACCEL_CANID     J1939_UCAST_ID(3, J1939_PGN_TSC1, J1939_DA_ENGINE, J1939_SA_HEADWAY_CTRL)
  #define CAN_SIM_COMMAND_ACCEL_PERIODMS  10
  #define CAN_SIM_COMMAND_ACCEL_IDTYPE    CAN_SIM_J1939_IDTYPE
  #define CAN_SIM_COMMAND_ACCEL_FORMAT    CAN_SIM_J1939_FORMAT
  #define CAN_SIM_COMMAND_ACCEL_BRS       CAN_SIM_J1939_BRS
  #define CAN_SIM_COMMAND_ACCEL_DLC       CAN_SIM_J1939_DLC
  #define CAN_SIM_COMMAND_ACCEL_PAYLOAD_OFFSET -1
  #define CAN_SIM_COMMAND_ACCEL_COUNTER_OFFSET -1
  #define CAN_SIM_COMMAND_ACCEL_CRC_OFFSET -1

  #define CAN_SIM_STATUS_RPM_CANID        J1939_BCAST_ID(3, J1939_PGN_EEC1, J1939_SA_HEADWAY_CTRL)
  #define CAN_SIM_STATUS_RPM_PERIODMS     20
  #define CAN_SIM_STATUS_RPM_IDTYPE       CAN_SIM_J1939_IDTYPE
  #define CAN_SIM_STATUS_RPM_FORMAT       CAN_SIM_J1939_FORMAT
  #define CAN_SIM_STATUS_RPM_BRS          CAN_SIM_J1939_BRS
  #define CAN_SIM_STATUS_RPM_DLC          CAN_SIM_J1939_DLC
  #define CAN_SIM_STATUS_RPM_PAYLOAD_OFFSET -1
  #define CAN_SIM_STATUS_RPM_COUNTER_OFFSET -1
  #define CAN_SIM_STATUS_RPM_CRC_OFFSET -1

  #define CAN_SIM_COMMAND_STEERING_CANID  J1939_UCAST_ID(2, J1939_PGN_PROPA, J1939_DA_STEERING_CTRL, J1939_SA_HEADWAY_CTRL)
  #define CAN_SIM_COMMAND_STEERING_PERIODMS 20
  #define CAN_SIM_COMMAND_STEERING_IDTYPE CAN_SIM_J1939_IDTYPE
  #define CAN_SIM_COMMAND_STEERING_FORMAT CAN_SIM_J1939_FORMAT
  #define CAN_SIM_COMMAND_STEERING_BRS    CAN_SIM_J1939_BRS
  #define CAN_SIM_COMMAND_STEERING_DLC    CAN_SIM_J1939_DLC
  #define CAN_SIM_COMMAND_STEERING_PAYLOAD_OFFSET -1
  #define CAN_SIM_COMMAND_STEERING_COUNTER_OFFSET -1
  #define CAN_SIM_COMMAND_STEERING_CRC_OFFSET -1

  #define CAN_SIM_COMMAND_SIDEBRAKE_CANID J1939_BCAST_ID(6, J1939_PGN_CCVS1, J1939_SA_HEADWAY_CTRL)
  #define CAN_SIM_COMMAND_SIDEBRAKE_PERIODMS 100
  #define CAN_SIM_COMMAND_SIDEBRAKE_IDTYPE CAN_SIM_J1939_IDTYPE
  #define CAN_SIM_COMMAND_SIDEBRAKE_FORMAT CAN_SIM_J1939_FORMAT
  #define CAN_SIM_COMMAND_SIDEBRAKE_BRS    CAN_SIM_J1939_BRS
  #define CAN_SIM_COMMAND_SIDEBRAKE_DLC    CAN_SIM_J1939_DLC
  #define CAN_SIM_COMMAND_SIDEBRAKE_PAYLOAD_OFFSET -1
  #define CAN_SIM_COMMAND_SIDEBRAKE_COUNTER_OFFSET -1
  #define CAN_SIM_COMMAND_SIDEBRAKE_CRC_OFFSET -1

  #define CAN_SIM_COMMAND_PARKINGBRAKE_CANID CAN_SIM_COMMAND_SIDEBRAKE_CANID
  #define CAN_SIM_COMMAND_PARKINGBRAKE_PERIODMS CAN_SIM_COMMAND_SIDEBRAKE_PERIODMS
  #define CAN_SIM_COMMAND_PARKINGBRAKE_IDTYPE CAN_SIM_COMMAND_SIDEBRAKE_IDTYPE
  #define CAN_SIM_COMMAND_PARKINGBRAKE_FORMAT CAN_SIM_COMMAND_SIDEBRAKE_FORMAT
  #define CAN_SIM_COMMAND_PARKINGBRAKE_BRS    CAN_SIM_COMMAND_SIDEBRAKE_BRS
  #define CAN_SIM_COMMAND_PARKINGBRAKE_DLC    CAN_SIM_COMMAND_SIDEBRAKE_DLC
  #define CAN_SIM_COMMAND_PARKINGBRAKE_PAYLOAD_OFFSET -1
  #define CAN_SIM_COMMAND_PARKINGBRAKE_COUNTER_OFFSET -1
  #define CAN_SIM_COMMAND_PARKINGBRAKE_CRC_OFFSET -1

  #define CAN_SIM_COMMAND_SHIFT_CANID     J1939_UCAST_ID(3, J1939_PGN_TC1, J1939_DA_TRANSMISSION, J1939_SA_HEADWAY_CTRL)
  #define CAN_SIM_COMMAND_SHIFT_PERIODMS  50
  #define CAN_SIM_COMMAND_SHIFT_IDTYPE    CAN_SIM_J1939_IDTYPE
  #define CAN_SIM_COMMAND_SHIFT_FORMAT    CAN_SIM_J1939_FORMAT
  #define CAN_SIM_COMMAND_SHIFT_BRS       CAN_SIM_J1939_BRS
  #define CAN_SIM_COMMAND_SHIFT_DLC       CAN_SIM_J1939_DLC
  #define CAN_SIM_COMMAND_SHIFT_PAYLOAD_OFFSET -1
  #define CAN_SIM_COMMAND_SHIFT_COUNTER_OFFSET -1
  #define CAN_SIM_COMMAND_SHIFT_CRC_OFFSET -1

  #define CAN_SIM_CONTROL_HORN_CANID      J1939_UCAST_ID(6, J1939_PGN_PROPA, J1939_DA_POWERTRAIN_CTRL, J1939_SA_HEADWAY_CTRL)
  #define CAN_SIM_CONTROL_HORN_PERIODMS   100
  #define CAN_SIM_CONTROL_HORN_IDTYPE     CAN_SIM_J1939_IDTYPE
  #define CAN_SIM_CONTROL_HORN_FORMAT     CAN_SIM_J1939_FORMAT
  #define CAN_SIM_CONTROL_HORN_BRS        CAN_SIM_J1939_BRS
  #define CAN_SIM_CONTROL_HORN_DLC        CAN_SIM_J1939_DLC
  #define CAN_SIM_CONTROL_HORN_PAYLOAD_OFFSET -1
  #define CAN_SIM_CONTROL_HORN_COUNTER_OFFSET -1
  #define CAN_SIM_CONTROL_HORN_CRC_OFFSET -1



#else
  #include "ramn_can_ids_default.h"
#endif

// This section defines which CAN ID an ECU is configured to receive.
// May be used to setup CAN filters.
#if defined(TARGET_ECUA)
#define RECEIVE_CONTROL_BRAKE
#define RECEIVE_CONTROL_ACCEL
#define RECEIVE_CONTROL_STEERING
#define RECEIVE_CONTROL_SHIFT
#define RECEIVE_JOYSTICK_BUTTONS
#define RECEIVE_CONTROL_SIDEBRAKE
#define RECEIVE_CONTROL_ENGINEKEY
#define RECEIVE_COMMAND_LIGHTS
#define RECEIVE_CONTROL_LIGHTS
#define RECEIVE_COMMAND_HORN
#elif defined(TARGET_ECUB)
#define RECEIVE_COMMAND_STEERING
#define RECEIVE_COMMAND_SIDEBRAKE
#define RECEIVE_COMMAND_LIGHTS
#define RECEIVE_STATUS_RPM
#elif defined(TARGET_ECUC)
#define RECEIVE_CONTROL_ENGINEKEY
#define RECEIVE_COMMAND_BRAKE
#define RECEIVE_COMMAND_ACCEL
#define RECEIVE_STATUS_RPM
#define RECEIVE_COMMAND_SIDEBRAKE
#define RECEIVE_COMMAND_SHIFT
#define RECEIVE_CONTROL_HORN
#elif defined(TARGET_ECUD)
#define RECEIVE_CONTROL_BRAKE
#define RECEIVE_CONTROL_SIDEBRAKE
#define RECEIVE_STATUS_RPM
#define RECEIVE_COMMAND_TURNINDICATOR
#define RECEIVE_COMMAND_LIGHTS
#endif

///////////////////////////////////////
// VEHICLE SPECIFIC DEFINITIONS END  //
///////////////////////////////////////

// Union that has both CAN header and data
typedef union
{
	uint8_t rawData[CAN_MAX_PAYLOAD_SIZE_DEFAULT];
} RAMN_CANFrameData_t;

// Structure that has both CAN header, data, and transmission information
typedef struct
{
	FDCAN_TxHeaderTypeDef header;
	RAMN_CANFrameData_t data[CAN_MAX_PAYLOAD_SIZE_DEFAULT];
	uint32_t periodms; // Target period for periodic transmission
	uint32_t counter;  // Number of time the message has been sent
	uint32_t lastSent; // Timestamp of last transmission
	int16_t payloadOffset;
	int16_t counterOffset;
	int16_t crcOffset;
} RAMN_PeriodicFDCANTx_t;

// Definition of messages that are periodically sent by ECU
#if defined(TARGET_ECUA)
extern RAMN_PeriodicFDCANTx_t msg_command_brake;
extern RAMN_PeriodicFDCANTx_t msg_command_accel;
extern RAMN_PeriodicFDCANTx_t msg_status_RPM;
extern RAMN_PeriodicFDCANTx_t msg_command_steering;
extern RAMN_PeriodicFDCANTx_t msg_command_shift;
extern RAMN_PeriodicFDCANTx_t msg_control_horn;
extern RAMN_PeriodicFDCANTx_t msg_command_horn;
extern RAMN_PeriodicFDCANTx_t msg_command_parkingbrake;
#endif

#if defined(TARGET_ECUB)
extern RAMN_PeriodicFDCANTx_t msg_control_steering;
extern RAMN_PeriodicFDCANTx_t msg_control_sidebrake;
extern RAMN_PeriodicFDCANTx_t msg_command_lights;
#endif

#if defined(TARGET_ECUC)
extern RAMN_PeriodicFDCANTx_t msg_control_brake;
extern RAMN_PeriodicFDCANTx_t msg_control_accel;
extern RAMN_PeriodicFDCANTx_t msg_control_shift;
extern RAMN_PeriodicFDCANTx_t msg_control_horn;
extern RAMN_PeriodicFDCANTx_t msg_command_horn;
extern RAMN_PeriodicFDCANTx_t msg_command_turnindicator;
#ifdef ENABLE_J1939_MODE
extern RAMN_PeriodicFDCANTx_t msg_joystick_buttons;
#endif
#endif

#if defined(TARGET_ECUD)

extern RAMN_PeriodicFDCANTx_t msg_control_enginekey;
extern RAMN_PeriodicFDCANTx_t msg_control_lights;
#endif

#endif /* INC_RAMN_VEHICLE_SPECIFIC_H_ */
