/*
 * ramn_can_ids_default.h
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2025 TOYOTA MOTOR CORPORATION.
 * ALL RIGHTS RESERVED.</center></h2>
 *
 * This software component is licensed by TOYOTA MOTOR CORPORATION under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#ifndef INC_RAMN_CAN_IDS_DEFAULT_H_
#define INC_RAMN_CAN_IDS_DEFAULT_H_

// Message specific settings
#define CAN_SIM_CONTROL_BRAKE_CANID               		0x24
#define CAN_SIM_CONTROL_BRAKE_PERIODMS		      		CAN_SIM_PERIODSMS_DEFAULT_FAST
#define CAN_SIM_CONTROL_BRAKE_IDTYPE 			  		CAN_SIM_IDTYPE_DEFAULT
#define CAN_SIM_CONTROL_BRAKE_FORMAT 			  		CAN_SIM_FORMAT_DEFAULT
#define CAN_SIM_CONTROL_BRAKE_BRS 				  		CAN_SIM_BRS_DEFAULT
#define CAN_SIM_CONTROL_BRAKE_DLC 				 		CAN_SIM_DLC_DEFAULT
#define CAN_SIM_CONTROL_BRAKE_PAYLOAD_OFFSET            RAMN_MSG_PAYLOAD_OFFSET
#define CAN_SIM_CONTROL_BRAKE_PAYLOAD_MASK              RAMN_MSG_PAYLOAD_MASK
#define CAN_SIM_CONTROL_BRAKE_COUNTER_OFFSET            RAMN_MSG_COUNTER_OFFSET
#define CAN_SIM_CONTROL_BRAKE_CRC_OFFSET                RAMN_MSG_CRC_OFFSET

#define CAN_SIM_CONTROL_ACCEL_CANID           	 		0x39
#define CAN_SIM_CONTROL_ACCEL_PERIODMS		 	 		CAN_SIM_PERIODSMS_DEFAULT_FAST
#define CAN_SIM_CONTROL_ACCEL_IDTYPE 		 	 		CAN_SIM_IDTYPE_DEFAULT
#define CAN_SIM_CONTROL_ACCEL_FORMAT 		 	 		CAN_SIM_FORMAT_DEFAULT
#define CAN_SIM_CONTROL_ACCEL_BRS 		         		CAN_SIM_BRS_DEFAULT
#define CAN_SIM_CONTROL_ACCEL_DLC 			 	 		CAN_SIM_DLC_DEFAULT
#define CAN_SIM_CONTROL_ACCEL_PAYLOAD_OFFSET            RAMN_MSG_PAYLOAD_OFFSET
#define CAN_SIM_CONTROL_ACCEL_PAYLOAD_MASK              RAMN_MSG_PAYLOAD_MASK
#define CAN_SIM_CONTROL_ACCEL_COUNTER_OFFSET            RAMN_MSG_COUNTER_OFFSET
#define CAN_SIM_CONTROL_ACCEL_CRC_OFFSET                RAMN_MSG_CRC_OFFSET

#define CAN_SIM_CONTROL_STEERING_CANID        			0x62
#define CAN_SIM_CONTROL_STEERING_PERIODMS		  		CAN_SIM_PERIODSMS_DEFAULT_FAST
#define CAN_SIM_CONTROL_STEERING_IDTYPE 				CAN_SIM_IDTYPE_DEFAULT
#define CAN_SIM_CONTROL_STEERING_FORMAT 				CAN_SIM_FORMAT_DEFAULT
#define CAN_SIM_CONTROL_STEERING_BRS 					CAN_SIM_BRS_DEFAULT
#define CAN_SIM_CONTROL_STEERING_DLC 					CAN_SIM_DLC_DEFAULT
#define CAN_SIM_CONTROL_STEERING_PAYLOAD_OFFSET            RAMN_MSG_PAYLOAD_OFFSET
#define CAN_SIM_CONTROL_STEERING_PAYLOAD_MASK              RAMN_MSG_PAYLOAD_MASK
#define CAN_SIM_CONTROL_STEERING_COUNTER_OFFSET            RAMN_MSG_COUNTER_OFFSET
#define CAN_SIM_CONTROL_STEERING_CRC_OFFSET                RAMN_MSG_CRC_OFFSET

#define CAN_SIM_CONTROL_SHIFT_CANID           			0x77
#define CAN_SIM_CONTROL_SHIFT_PERIODMS		 			CAN_SIM_PERIODSMS_DEFAULT
#define CAN_SIM_CONTROL_SHIFT_IDTYPE 					CAN_SIM_IDTYPE_DEFAULT
#define CAN_SIM_CONTROL_SHIFT_FORMAT 					CAN_SIM_FORMAT_DEFAULT
#define CAN_SIM_CONTROL_SHIFT_BRS 						CAN_SIM_BRS_DEFAULT
#define CAN_SIM_CONTROL_SHIFT_DLC 						CAN_SIM_DLC_DEFAULT
#define CAN_SIM_CONTROL_SHIFT_PAYLOAD_OFFSET            RAMN_MSG_PAYLOAD_OFFSET
#define CAN_SIM_CONTROL_SHIFT_PAYLOAD_MASK              RAMN_MSG_PAYLOAD_MASK
#define CAN_SIM_CONTROL_SHIFT_COUNTER_OFFSET            RAMN_MSG_COUNTER_OFFSET
#define CAN_SIM_CONTROL_SHIFT_CRC_OFFSET                RAMN_MSG_CRC_OFFSET

#define CAN_SIM_COMMAND_HORN_CANID            			0x98
#define CAN_SIM_COMMAND_HORN_CANID_PERIODMS		  		CAN_SIM_PERIODSMS_DEFAULT
#define CAN_SIM_COMMAND_HORN_CANID_IDTYPE 				CAN_SIM_IDTYPE_DEFAULT
#define CAN_SIM_COMMAND_HORN_CANID_FORMAT 				CAN_SIM_FORMAT_DEFAULT
#define CAN_SIM_COMMAND_HORN_CANID_BRS 					CAN_SIM_BRS_DEFAULT
#define CAN_SIM_COMMAND_HORN_CANID_DLC 					CAN_SIM_DLC_DEFAULT
#define CAN_SIM_COMMAND_HORN_PAYLOAD_OFFSET            RAMN_MSG_PAYLOAD_OFFSET
#define CAN_SIM_COMMAND_HORN_PAYLOAD_MASK              0xFF
#define CAN_SIM_COMMAND_HORN_COUNTER_OFFSET            RAMN_MSG_COUNTER_OFFSET
#define CAN_SIM_COMMAND_HORN_CRC_OFFSET                RAMN_MSG_CRC_OFFSET

#define CAN_SIM_CONTROL_SIDEBRAKE_CANID       			0x1D3
#define CAN_SIM_CONTROL_SIDEBRAKE_PERIODMS		  		CAN_SIM_PERIODSMS_DEFAULT
#define CAN_SIM_CONTROL_SIDEBRAKE_IDTYPE 				CAN_SIM_IDTYPE_DEFAULT
#define CAN_SIM_CONTROL_SIDEBRAKE_FORMAT 				CAN_SIM_FORMAT_DEFAULT
#define CAN_SIM_CONTROL_SIDEBRAKE_BRS 					CAN_SIM_BRS_DEFAULT
#define CAN_SIM_CONTROL_SIDEBRAKE_DLC 					CAN_SIM_DLC_DEFAULT
#define CAN_SIM_CONTROL_SIDEBRAKE_PAYLOAD_OFFSET            RAMN_MSG_PAYLOAD_OFFSET
#define CAN_SIM_CONTROL_SIDEBRAKE_PAYLOAD_MASK              0xFF
#define CAN_SIM_CONTROL_SIDEBRAKE_COUNTER_OFFSET            RAMN_MSG_COUNTER_OFFSET
#define CAN_SIM_CONTROL_SIDEBRAKE_CRC_OFFSET                RAMN_MSG_CRC_OFFSET

#define CAN_SIM_COMMAND_TURNINDICATOR_CANID   		  	0x1A7
#define CAN_SIM_COMMAND_TURNINDICATOR_PERIODMS		  	CAN_SIM_PERIODSMS_DEFAULT
#define CAN_SIM_COMMAND_TURNINDICATOR_IDTYPE 		  	CAN_SIM_IDTYPE_DEFAULT
#define CAN_SIM_COMMAND_TURNINDICATOR_FORMAT 		  	CAN_SIM_FORMAT_DEFAULT
#define CAN_SIM_COMMAND_TURNINDICATOR_BRS 			  	CAN_SIM_BRS_DEFAULT
#define CAN_SIM_COMMAND_TURNINDICATOR_DLC 			  	CAN_SIM_DLC_DEFAULT
#define CAN_SIM_COMMAND_TURNINDICATOR_PAYLOAD_OFFSET            RAMN_MSG_PAYLOAD_OFFSET
#define CAN_SIM_COMMAND_TURNINDICATOR_PAYLOAD_MASK              RAMN_MSG_PAYLOAD_MASK
#define CAN_SIM_COMMAND_TURNINDICATOR_COUNTER_OFFSET            RAMN_MSG_COUNTER_OFFSET
#define CAN_SIM_COMMAND_TURNINDICATOR_CRC_OFFSET                RAMN_MSG_CRC_OFFSET

#define CAN_SIM_CONTROL_ENGINEKEY_CANID		  			0x1B8
#define CAN_SIM_CONTROL_ENGINEKEY_PERIODMS		  		CAN_SIM_PERIODSMS_DEFAULT
#define CAN_SIM_CONTROL_ENGINEKEY_IDTYPE 				CAN_SIM_IDTYPE_DEFAULT
#define CAN_SIM_CONTROL_ENGINEKEY_FORMAT 				CAN_SIM_FORMAT_DEFAULT
#define CAN_SIM_CONTROL_ENGINEKEY_BRS 					CAN_SIM_BRS_DEFAULT
#define CAN_SIM_CONTROL_ENGINEKEY_DLC 					CAN_SIM_DLC_DEFAULT
#define CAN_SIM_CONTROL_ENGINEKEY_PAYLOAD_OFFSET            RAMN_MSG_PAYLOAD_OFFSET
#define CAN_SIM_CONTROL_ENGINEKEY_PAYLOAD_MASK              0xFF
#define CAN_SIM_CONTROL_ENGINEKEY_COUNTER_OFFSET            RAMN_MSG_COUNTER_OFFSET
#define CAN_SIM_CONTROL_ENGINEKEY_CRC_OFFSET                RAMN_MSG_CRC_OFFSET

#define CAN_SIM_COMMAND_LIGHTS_CANID	      			0x150
#define CAN_SIM_COMMAND_LIGHTS_PERIODMS		  			CAN_SIM_PERIODSMS_DEFAULT
#define CAN_SIM_COMMAND_LIGHTS_IDTYPE 					CAN_SIM_IDTYPE_DEFAULT
#define CAN_SIM_COMMAND_LIGHTS_FORMAT 					CAN_SIM_FORMAT_DEFAULT
#define CAN_SIM_COMMAND_LIGHTS_BRS 						CAN_SIM_BRS_DEFAULT
#define CAN_SIM_COMMAND_LIGHTS_DLC 						CAN_SIM_DLC_DEFAULT
#define CAN_SIM_COMMAND_LIGHTS_PAYLOAD_OFFSET            RAMN_MSG_PAYLOAD_OFFSET
#define CAN_SIM_COMMAND_LIGHTS_PAYLOAD_MASK              RAMN_MSG_PAYLOAD_MASK
#define CAN_SIM_COMMAND_LIGHTS_COUNTER_OFFSET            RAMN_MSG_COUNTER_OFFSET
#define CAN_SIM_COMMAND_LIGHTS_CRC_OFFSET                RAMN_MSG_CRC_OFFSET

#define CAN_SIM_CONTROL_LIGHTS_CANID          			0x1BB
#define CAN_SIM_CONTROL_LIGHTS_PERIODMS		  			CAN_SIM_PERIODSMS_DEFAULT
#define CAN_SIM_CONTROL_LIGHTS_IDTYPE 					CAN_SIM_IDTYPE_DEFAULT
#define CAN_SIM_CONTROL_LIGHTS_FORMAT 					CAN_SIM_FORMAT_DEFAULT
#define CAN_SIM_CONTROL_LIGHTS_BRS 						CAN_SIM_BRS_DEFAULT
#define CAN_SIM_CONTROL_LIGHTS_DLC 						CAN_SIM_DLC_DEFAULT
#define CAN_SIM_CONTROL_LIGHTS_PAYLOAD_OFFSET            RAMN_MSG_PAYLOAD_OFFSET
#define CAN_SIM_CONTROL_LIGHTS_PAYLOAD_MASK              0xFF
#define CAN_SIM_CONTROL_LIGHTS_COUNTER_OFFSET            RAMN_MSG_COUNTER_OFFSET
#define CAN_SIM_CONTROL_LIGHTS_CRC_OFFSET                RAMN_MSG_CRC_OFFSET

#define CAN_SIM_COMMAND_BRAKE_CANID			  			0x1A
#define CAN_SIM_COMMAND_BRAKE_PERIODMS		  			CAN_SIM_PERIODSMS_DEFAULT_FAST
#define CAN_SIM_COMMAND_BRAKE_IDTYPE 					CAN_SIM_IDTYPE_DEFAULT
#define CAN_SIM_COMMAND_BRAKE_FORMAT 					CAN_SIM_FORMAT_DEFAULT
#define CAN_SIM_COMMAND_BRAKE_BRS 						CAN_SIM_BRS_DEFAULT
#define CAN_SIM_COMMAND_BRAKE_DLC 						CAN_SIM_DLC_DEFAULT
#define CAN_SIM_COMMAND_BRAKE_PAYLOAD_OFFSET            RAMN_MSG_PAYLOAD_OFFSET
#define CAN_SIM_COMMAND_BRAKE_PAYLOAD_MASK              RAMN_MSG_PAYLOAD_MASK
#define CAN_SIM_COMMAND_BRAKE_COUNTER_OFFSET            RAMN_MSG_COUNTER_OFFSET
#define CAN_SIM_COMMAND_BRAKE_CRC_OFFSET                RAMN_MSG_CRC_OFFSET

#define CAN_SIM_COMMAND_ACCEL_CANID		      			0x2F
#define CAN_SIM_COMMAND_ACCEL_PERIODMS		  			CAN_SIM_PERIODSMS_DEFAULT_FAST
#define CAN_SIM_COMMAND_ACCEL_IDTYPE 					CAN_SIM_IDTYPE_DEFAULT
#define CAN_SIM_COMMAND_ACCEL_FORMAT 					CAN_SIM_FORMAT_DEFAULT
#define CAN_SIM_COMMAND_ACCEL_BRS 						CAN_SIM_BRS_DEFAULT
#define CAN_SIM_COMMAND_ACCEL_DLC 						CAN_SIM_DLC_DEFAULT
#define CAN_SIM_COMMAND_ACCEL_PAYLOAD_OFFSET            RAMN_MSG_PAYLOAD_OFFSET
#define CAN_SIM_COMMAND_ACCEL_PAYLOAD_MASK              RAMN_MSG_PAYLOAD_MASK
#define CAN_SIM_COMMAND_ACCEL_COUNTER_OFFSET            RAMN_MSG_COUNTER_OFFSET
#define CAN_SIM_COMMAND_ACCEL_CRC_OFFSET                RAMN_MSG_CRC_OFFSET

#define CAN_SIM_STATUS_RPM_CANID			  			0x43
#define CAN_SIM_STATUS_RPM_PERIODMS		  				CAN_SIM_PERIODSMS_DEFAULT_FAST
#define CAN_SIM_STATUS_RPM_IDTYPE 						CAN_SIM_IDTYPE_DEFAULT
#define CAN_SIM_STATUS_RPM_FORMAT 						CAN_SIM_FORMAT_DEFAULT
#define CAN_SIM_STATUS_RPM_BRS 							CAN_SIM_BRS_DEFAULT
#define CAN_SIM_STATUS_RPM_DLC 							CAN_SIM_DLC_DEFAULT
#define CAN_SIM_STATUS_RPM_PAYLOAD_OFFSET            RAMN_MSG_PAYLOAD_OFFSET
#define CAN_SIM_STATUS_RPM_PAYLOAD_MASK              RAMN_MSG_PAYLOAD_MASK
#define CAN_SIM_STATUS_RPM_COUNTER_OFFSET            RAMN_MSG_COUNTER_OFFSET
#define CAN_SIM_STATUS_RPM_CRC_OFFSET                RAMN_MSG_CRC_OFFSET

#define CAN_SIM_COMMAND_STEERING_CANID		  			0x58
#define CAN_SIM_COMMAND_STEERING_PERIODMS		  		CAN_SIM_PERIODSMS_DEFAULT_FAST
#define CAN_SIM_COMMAND_STEERING_IDTYPE 				CAN_SIM_IDTYPE_DEFAULT
#define CAN_SIM_COMMAND_STEERING_FORMAT 				CAN_SIM_FORMAT_DEFAULT
#define CAN_SIM_COMMAND_STEERING_BRS 					CAN_SIM_BRS_DEFAULT
#define CAN_SIM_COMMAND_STEERING_DLC 					CAN_SIM_DLC_DEFAULT
#define CAN_SIM_COMMAND_STEERING_PAYLOAD_OFFSET            RAMN_MSG_PAYLOAD_OFFSET
#define CAN_SIM_COMMAND_STEERING_PAYLOAD_MASK              RAMN_MSG_PAYLOAD_MASK
#define CAN_SIM_COMMAND_STEERING_COUNTER_OFFSET            RAMN_MSG_COUNTER_OFFSET
#define CAN_SIM_COMMAND_STEERING_CRC_OFFSET                RAMN_MSG_CRC_OFFSET

#define CAN_SIM_COMMAND_SIDEBRAKE_CANID	      			0x1C9
#define CAN_SIM_COMMAND_SIDEBRAKE_PERIODMS		  		CAN_SIM_PERIODSMS_DEFAULT
#define CAN_SIM_COMMAND_SIDEBRAKE_IDTYPE 				CAN_SIM_IDTYPE_DEFAULT
#define CAN_SIM_COMMAND_SIDEBRAKE_FORMAT 				CAN_SIM_FORMAT_DEFAULT
#define CAN_SIM_COMMAND_SIDEBRAKE_BRS 					CAN_SIM_BRS_DEFAULT
#define CAN_SIM_COMMAND_SIDEBRAKE_DLC 					CAN_SIM_DLC_DEFAULT
#define CAN_SIM_COMMAND_SIDEBRAKE_PAYLOAD_OFFSET            RAMN_MSG_PAYLOAD_OFFSET
#define CAN_SIM_COMMAND_SIDEBRAKE_PAYLOAD_MASK              RAMN_MSG_PAYLOAD_MASK
#define CAN_SIM_COMMAND_SIDEBRAKE_COUNTER_OFFSET            RAMN_MSG_COUNTER_OFFSET
#define CAN_SIM_COMMAND_SIDEBRAKE_CRC_OFFSET                RAMN_MSG_CRC_OFFSET

#define CAN_SIM_COMMAND_SHIFT_CANID 		  			0x6D
#define CAN_SIM_COMMAND_SHIFT_PERIODMS		  			CAN_SIM_PERIODSMS_DEFAULT
#define CAN_SIM_COMMAND_SHIFT_IDTYPE 					CAN_SIM_IDTYPE_DEFAULT
#define CAN_SIM_COMMAND_SHIFT_FORMAT 					CAN_SIM_FORMAT_DEFAULT
#define CAN_SIM_COMMAND_SHIFT_BRS 						CAN_SIM_BRS_DEFAULT
#define CAN_SIM_COMMAND_SHIFT_DLC 						CAN_SIM_DLC_DEFAULT
#define CAN_SIM_COMMAND_SHIFT_PAYLOAD_OFFSET            RAMN_MSG_PAYLOAD_OFFSET
#define CAN_SIM_COMMAND_SHIFT_PAYLOAD_MASK              0xFF
#define CAN_SIM_COMMAND_SHIFT_COUNTER_OFFSET            RAMN_MSG_COUNTER_OFFSET
#define CAN_SIM_COMMAND_SHIFT_CRC_OFFSET                RAMN_MSG_CRC_OFFSET

#define CAN_SIM_CONTROL_HORN_CANID            			0xA2
#define CAN_SIM_CONTROL_HORN_PERIODMS		  			CAN_SIM_PERIODSMS_DEFAULT
#define CAN_SIM_CONTROL_HORN_IDTYPE 					CAN_SIM_IDTYPE_DEFAULT
#define CAN_SIM_CONTROL_HORN_FORMAT 					CAN_SIM_FORMAT_DEFAULT
#define CAN_SIM_CONTROL_HORN_BRS 						CAN_SIM_BRS_DEFAULT
#define CAN_SIM_CONTROL_HORN_DLC 						CAN_SIM_DLC_DEFAULT
#define CAN_SIM_CONTROL_HORN_PAYLOAD_OFFSET            RAMN_MSG_PAYLOAD_OFFSET
#define CAN_SIM_CONTROL_HORN_PAYLOAD_MASK              0xFF
#define CAN_SIM_CONTROL_HORN_COUNTER_OFFSET            RAMN_MSG_COUNTER_OFFSET
#define CAN_SIM_CONTROL_HORN_CRC_OFFSET                RAMN_MSG_CRC_OFFSET

#endif /* INC_RAMN_CAN_IDS_DEFAULT_H_ */
